### PR TITLE
FIX:  Python 3x compatibility. All works!

### PR DESCRIPTION
**Pull request by asakasinsky**
**Sorry, guys!**

I inadvertently put waste piece of code by copy-n-paste from project. And I have not tested it before commit, sorry. I fixed this.

**Description:**
- changed 'print' to 'print()'
  - added  relative import
  - added 'plugin_loaded' trigger (http://www.sublimetext.com/docs/3/api_reference.html)
  - changed open file method

**Note:**
    - I'm not tested this with non-unicode files
        - Maybe I'm not doing it right, because usually maintainer creates new branch as 'ST3' (if plugin is not crossversion), and other users use it via 'git checkout'. But only one branch here...

### CODE REVIEW

**Comment by joelpt** [comment]
Thanks for this contribution. The plugin is now updated for ST3. I won't be merging this pull request directly as I did some broader cleanup and used a different pattern for settings than in your version. Cheers!

**Comment by asakasinsky** [comment]
Thanks. But is still bad version  package in the ST Package Manager.

**Comment by joelpt** [comment]
The version package stuff should be fixed now and working for both ST2 and ST3. Please let me know if not.

**Comment by asakasinsky** [comment]
Error reporting:

on ST load:

``` txt
reloading plugin Automatic Backups.AutomaticBackups
reloading plugin Automatic Backups.backup_paths
reloading plugin Automatic Backups.backups_navigator
reloading plugin Automatic Backups.settings
reloading plugin Automatic Backups.win32helpers
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "win32helpers in /Users/asakasinsky/Library/Application Support/Sublime Text 3/Installed Packages/Automatic Backups.sublime-package", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "./ctypes/wintypes.py", line 20, in <module>
ValueError: _type_ 'v' not supported
```

on «back» action:

``` txt
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "AutomaticBackups in /Users/asakasinsky/Library/Application Support/Sublime Text 3/Installed Packages/Automatic Backups.sublime-package", line 117, in run
  File "backups_navigator in /Users/asakasinsky/Library/Application Support/Sublime Text 3/Installed Packages/Automatic Backups.sublime-package", line 83, in load_backup_to_view
  File "./encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 4498: ordinal not in range(128)

```

Version of the package from https://github.com/asakasinsky/sublimetext-automatic-backups/tree/ST3
 works.

**Pull request closed without merging**
